// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ritter.Samples.Infra.Data;

namespace Ritter.Samples.Infra.Data.Migrations
{
    [DbContext(typeof(SampleContext))]
    [Migration("20190325145213_01-Initial")]
    partial class _01Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Ritter.Samples.Domain.Aggregates.People.Document", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnName("person_id");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnName("number")
                        .HasMaxLength(20);

                    b.Property<int>("Type")
                        .HasColumnName("type");

                    b.Property<Guid>("Uid")
                        .HasColumnName("uid");

                    b.HasKey("Id");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("Ritter.Samples.Domain.Aggregates.People.Person", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("person_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("Uid")
                        .HasColumnName("uid");

                    b.HasKey("Id");

                    b.ToTable("People");
                });

            modelBuilder.Entity("Ritter.Samples.Domain.Aggregates.People.Document", b =>
                {
                    b.HasOne("Ritter.Samples.Domain.Aggregates.People.Person", "Person")
                        .WithOne("Cpf")
                        .HasForeignKey("Ritter.Samples.Domain.Aggregates.People.Document", "Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Ritter.Samples.Domain.Aggregates.People.Person", b =>
                {
                    b.OwnsOne("Ritter.Samples.Domain.Aggregates.People.Name", "Name", b1 =>
                        {
                            b1.Property<long>("PersonId")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasColumnName("first_name")
                                .HasMaxLength(50);

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasColumnName("last_name")
                                .HasMaxLength(50);

                            b1.HasKey("PersonId");

                            b1.ToTable("People");

                            b1.HasOne("Ritter.Samples.Domain.Aggregates.People.Person")
                                .WithOne("Name")
                                .HasForeignKey("Ritter.Samples.Domain.Aggregates.People.Name", "PersonId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
