// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace Aritter.Manager.Infrastructure.Data.Migrations
{
	[GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class M006 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(M006));
        
        string IMigrationMetadata.Id
        {
            get { return "201506050212352_M006"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
