// <auto-generated />
namespace Aritter.Infra.Data.Migrations
{
	using System.CodeDom.Compiler;
	using System.Data.Entity.Migrations.Infrastructure;
	using System.Resources;

	[GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
	internal sealed partial class V001 : IMigrationMetadata
	{
		private readonly ResourceManager Resources = new ResourceManager(typeof(V001));

		string IMigrationMetadata.Id
		{
			get { return "201508200225150_V0.0.1"; }
		}

		string IMigrationMetadata.Source
		{
			get { return null; }
		}

		string IMigrationMetadata.Target
		{
			get { return Resources.GetString("Target"); }
		}
	}
}
